name: Laravel

on:
  push:
    branches:
      # Change 'main' to your default branch name if it's different

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1' # Adjust the version as needed

      - name: Install npm dependencies
        run: npm install

      - name: Check if in CI environment
        id: check_ci
        run: echo ::set-output name=is_ci::${{ runner.os }}-${{ github.event_name }}

      - name: Run npm dev to generate Vite manifest
        if: ${{ !steps.check_ci.outputs.is_ci }}
        run: npm run dev

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --env=testing --force

      - name: Execute tests
        run: php artisan test
